name: Run MACD Script

on:
  workflow_dispatch:
  schedule:
    - cron: '10 9 * * 1-5' # 4:15 AM ET, Monday to Friday

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.12]  # Choose your desired Python version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with your requirements file if needed

    - name: Run Python script
      run: python macd.py  # Replace with your script filename
      env:
        GOOGLE_SHEETS_MACD_URL: ${{ secrets.GOOGLE_SHEETS_MACD_URL }}
